# Generated by Django 3.1.1 on 2020-09-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='type',
            field=models.CharField(choices=[('PRI', 'Primary School'), ('SEC', 'Secondary School'), ('UNI', 'University'), ('COL', 'College'), ('HS', 'High School')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
