# Generated by Django 3.1.1 on 2020-09-20 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_backend', '0002_school_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='type',
            new_name='school_type',
        ),
    ]
